import "../../App.css";
import QuestionBox from "../../components/QuestionBox/QuestionBox";
import "./FAQ.css";
export default function FAQ() {
    const questions = getSampleQuestions();
    return (
        <div className="App">
            <div className="topic-box">
                <div style={{
                    backdropFilter: "blur(20px)",
                    backgroundColor: "#f19a1644",
                    padding: "20px"
                }}>
                    <h1 style={{ color: "#fff" }}>Frequently Asked Questions</h1>
                </div>

            </div>
            <div className="qa-container">
                {questions.map(question => (
                    <QuestionBox key={question.id} question={question} />
                ))}
            </div>
            <header className="App-header">

            </header>
        </div>);
}


const getSampleQuestions = () => {
    return [
        {
            "id": 1,
            "question": "How far in advance should I book your services?",
            "answer": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lorem est, faucibus mattis arcu vel, congue iaculis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec feugiat tincidunt diam ac faucibus. Quisque ut euismod est, id dignissim nisi. Maecenas at nisl a lectus lobortis bibendum accumsan porta neque. Nullam lectus urna, scelerisque eu egestas in, iaculis id nisi. Morbi tincidunt, libero sed placerat facilisis, lacus mi laoreet odio, eget convallis mauris lectus eu velit. Vivamus ut bibendum quam. Suspendisse sapien eros, tristique et diam quis, semper cursus eros. Donec feugiat, orci ac tincidunt ultricies, libero ipsum elementum purus, in semper ex enim vitae erat. Mauris mi nulla, tempor rhoncus tortor vel, efficitur gravida mi. Suspendisse potenti.Fusce tristique ultricies lectus, vel vehicula ante mattis sed. Vestibulum metus turpis, tristique non convallis id, blandit vel dui. Aliquam sit amet tincidunt orci, at lobortis ipsum. Cras rhoncus maximus sem at pretium. Integer tempor nunc sem, eu pellentesque mauris gravida sed. Pellentesque vel congue odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus volutpat felis in sem dapibus, quis pretium metus pharetra. Sed suscipit pretium sem, ornare tempus risus faucibus ac. Vestibulum sodales risus eget placerat sagittis. Etiam sed arcu id felis posuere consectetur. Etiam ut justo condimentum nisl ultrices dictum nec vitae sapien. Nulla blandit augue turpis, ut tincidunt est semper in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Aliquam erat volutpat. Sed felis elit, commodo vehicula mauris nec, porta vehicula mi. Duis nisi nunc, congue vitae tincidunt ut, semper elementum risus. Morbi neque metus, bibendum a finibus vel, maximus sed tortor. Nunc semper justo sed tellus faucibus ullamcorper. Integer quis ipsum ac lorem ultrices tincidunt. Sed iaculis mattis malesuada. Sed ac lacus sodales, blandit nunc nec, elementum mi. Ut nec placerat odio, ac mattis massa. Vivamus a interdum nisi. Suspendisse porttitor diam vel fringilla vestibulum. Nullam est elit, placerat eu metus a, elementum aliquam erat. Fusce ut nisi tortor. Nam tincidunt sed velit sed efficitur. Maecenas quam ligula, egestas sit amet felis ut, volutpat sagittis tellus."
        },
        {
            "id": 2,
            "question": "Can you help with both corporate and private events?",
            "answer": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lorem est, faucibus mattis arcu vel, congue iaculis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec feugiat tincidunt diam ac faucibus. Quisque ut euismod est, id dignissim nisi. Maecenas at nisl a lectus lobortis bibendum accumsan porta neque. Nullam lectus urna, scelerisque eu egestas in, iaculis id nisi. Morbi tincidunt, libero sed placerat facilisis, lacus mi laoreet odio, eget convallis mauris lectus eu velit. Vivamus ut bibendum quam. Suspendisse sapien eros, tristique et diam quis, semper cursus eros. Donec feugiat, orci ac tincidunt ultricies, libero ipsum elementum purus, in semper ex enim vitae erat. Mauris mi nulla, tempor rhoncus tortor vel, efficitur gravida mi. Suspendisse potenti.Fusce tristique ultricies lectus, vel vehicula ante mattis sed. Vestibulum metus turpis, tristique non convallis id, blandit vel dui. Aliquam sit amet tincidunt orci, at lobortis ipsum. Cras rhoncus maximus sem at pretium. Integer tempor nunc sem, eu pellentesque mauris gravida sed. Pellentesque vel congue odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus volutpat felis in sem dapibus, quis pretium metus pharetra. Sed suscipit pretium sem, ornare tempus risus faucibus ac. Vestibulum sodales risus eget placerat sagittis. Etiam sed arcu id felis posuere consectetur. Etiam ut justo condimentum nisl ultrices dictum nec vitae sapien. Nulla blandit augue turpis, ut tincidunt est semper in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Aliquam erat volutpat. Sed felis elit, commodo vehicula mauris nec, porta vehicula mi. Duis nisi nunc, congue vitae tincidunt ut, semper elementum risus. Morbi neque metus, bibendum a finibus vel, maximus sed tortor. Nunc semper justo sed tellus faucibus ullamcorper. Integer quis ipsum ac lorem ultrices tincidunt. Sed iaculis mattis malesuada. Sed ac lacus sodales, blandit nunc nec, elementum mi. Ut nec placerat odio, ac mattis massa. Vivamus a interdum nisi. Suspendisse porttitor diam vel fringilla vestibulum. Nullam est elit, placerat eu metus a, elementum aliquam erat. Fusce ut nisi tortor. Nam tincidunt sed velit sed efficitur. Maecenas quam ligula, egestas sit amet felis ut, volutpat sagittis tellus."
        },
        {
            "id": 3,
            "question": "What are the payment terms and methods accepted?",
            "answer": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lorem est, faucibus mattis arcu vel, congue iaculis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec feugiat tincidunt diam ac faucibus. Quisque ut euismod est, id dignissim nisi. Maecenas at nisl a lectus lobortis bibendum accumsan porta neque. Nullam lectus urna, scelerisque eu egestas in, iaculis id nisi. Morbi tincidunt, libero sed placerat facilisis, lacus mi laoreet odio, eget convallis mauris lectus eu velit. Vivamus ut bibendum quam. Suspendisse sapien eros, tristique et diam quis, semper cursus eros. Donec feugiat, orci ac tincidunt ultricies, libero ipsum elementum purus, in semper ex enim vitae erat. Mauris mi nulla, tempor rhoncus tortor vel, efficitur gravida mi. Suspendisse potenti.Fusce tristique ultricies lectus, vel vehicula ante mattis sed. Vestibulum metus turpis, tristique non convallis id, blandit vel dui. Aliquam sit amet tincidunt orci, at lobortis ipsum. Cras rhoncus maximus sem at pretium. Integer tempor nunc sem, eu pellentesque mauris gravida sed. Pellentesque vel congue odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus volutpat felis in sem dapibus, quis pretium metus pharetra. Sed suscipit pretium sem, ornare tempus risus faucibus ac. Vestibulum sodales risus eget placerat sagittis. Etiam sed arcu id felis posuere consectetur. Etiam ut justo condimentum nisl ultrices dictum nec vitae sapien. Nulla blandit augue turpis, ut tincidunt est semper in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Aliquam erat volutpat. Sed felis elit, commodo vehicula mauris nec, porta vehicula mi. Duis nisi nunc, congue vitae tincidunt ut, semper elementum risus. Morbi neque metus, bibendum a finibus vel, maximus sed tortor. Nunc semper justo sed tellus faucibus ullamcorper. Integer quis ipsum ac lorem ultrices tincidunt. Sed iaculis mattis malesuada. Sed ac lacus sodales, blandit nunc nec, elementum mi. Ut nec placerat odio, ac mattis massa. Vivamus a interdum nisi. Suspendisse porttitor diam vel fringilla vestibulum. Nullam est elit, placerat eu metus a, elementum aliquam erat. Fusce ut nisi tortor. Nam tincidunt sed velit sed efficitur. Maecenas quam ligula, egestas sit amet felis ut, volutpat sagittis tellus."
        },
        {
            "id": 4,
            "question": "What happens if I need to cancel or reschedule my event?",
            "answer": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lorem est, faucibus mattis arcu vel, congue iaculis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec feugiat tincidunt diam ac faucibus. Quisque ut euismod est, id dignissim nisi. Maecenas at nisl a lectus lobortis bibendum accumsan porta neque. Nullam lectus urna, scelerisque eu egestas in, iaculis id nisi. Morbi tincidunt, libero sed placerat facilisis, lacus mi laoreet odio, eget convallis mauris lectus eu velit. Vivamus ut bibendum quam. Suspendisse sapien eros, tristique et diam quis, semper cursus eros. Donec feugiat, orci ac tincidunt ultricies, libero ipsum elementum purus, in semper ex enim vitae erat. Mauris mi nulla, tempor rhoncus tortor vel, efficitur gravida mi. Suspendisse potenti.Fusce tristique ultricies lectus, vel vehicula ante mattis sed. Vestibulum metus turpis, tristique non convallis id, blandit vel dui. Aliquam sit amet tincidunt orci, at lobortis ipsum. Cras rhoncus maximus sem at pretium. Integer tempor nunc sem, eu pellentesque mauris gravida sed. Pellentesque vel congue odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus volutpat felis in sem dapibus, quis pretium metus pharetra. Sed suscipit pretium sem, ornare tempus risus faucibus ac. Vestibulum sodales risus eget placerat sagittis. Etiam sed arcu id felis posuere consectetur. Etiam ut justo condimentum nisl ultrices dictum nec vitae sapien. Nulla blandit augue turpis, ut tincidunt est semper in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Aliquam erat volutpat. Sed felis elit, commodo vehicula mauris nec, porta vehicula mi. Duis nisi nunc, congue vitae tincidunt ut, semper elementum risus. Morbi neque metus, bibendum a finibus vel, maximus sed tortor. Nunc semper justo sed tellus faucibus ullamcorper. Integer quis ipsum ac lorem ultrices tincidunt. Sed iaculis mattis malesuada. Sed ac lacus sodales, blandit nunc nec, elementum mi. Ut nec placerat odio, ac mattis massa. Vivamus a interdum nisi. Suspendisse porttitor diam vel fringilla vestibulum. Nullam est elit, placerat eu metus a, elementum aliquam erat. Fusce ut nisi tortor. Nam tincidunt sed velit sed efficitur. Maecenas quam ligula, egestas sit amet felis ut, volutpat sagittis tellus."
        },
    ];
};